<scenario>
start=custom
weapon1= 999
weapon6= 64
worth=-10
</scenario>
<levels>
<custom>
name=Your Own Custom Massacre
bgpic=storm.bmp
sngname=music3.wav
timelimit=30
weather=rain
fground=fore1.bmp
pale=8
white=14
float=16
next=end
</custom>
</levels>
<fairies>

<gimp>
name=The Gimp Cat
fpic=gimpcat.bmp
dpic=catdie1.bmp
class=1
size=92
speed=150
intel=0
worth=-5000
fdie1=cdie.wav
fdie2=fdie6.wav
</gimp>

<bird>
name=Flyin Bird
fpic=bird.bmp
dpic=bird.bmp
class=3
speed=150
intel=0
worth=-5000
fdie1=cdie.wav
fdie2=fdie6.wav
</bird>


<fatboy>
name=Fat Jimmy and his Dog
fpic=boydog.bmp
dpic=boydogd1.bmp
class=1
size=92
speed=150
hp=15000
intel=0
worth=-10000
fdie1=bdie.wav
fdie2=fdie8.wav
</fatboy>

<green>
name=Slimey Sam, the Green Guy
fpic=fairy3.bmp
dpic=fairy3d1.bmp
apic=fairy3a.bmp
rprob=2
asound=wee.wav
size=60
worth=25
speed=50
intel=3
fdie1=fdie1.wav
fdie2=fdie8.wav
</green>

<pale>
name=Our Paley Friend
fpic=fairy10.bmp
dpic=fairy10d1.bmp
apic=fairy10a.bmp
rprob=2
worth=25
speed=50
intel=3
hp=5
fdie1=fdie1.wav
fdie2=fdie8.wav
</pale>

<blue>
name='Lil Bastard
fpic=fairy2.bmp
dpic=fairy2d1.bmp
worth=1000
size=50
speed=750
intel=10
hp=2
fdie1=fdie1.wav
fdie2=fdie7.wav
</blue>

<screech>
name=The Amazing Screech Owl
fpic=screechowl.bmp
dpic=screechowld1.bmp
apic=screechowls.bmp
rprob=5
asound=screech.wav
worth=-1000
speed=0
intel=0
class=2
hp=2
fdie1=owld1.wav
fdie2=owld1.wav
</screech>

<white>
name=Snow White
fpic=fairy1.bmp
dpic=fairy1d1.bmp
worth=25
speed=150
intel=10
hp=2
fdie1=fdie4.wav
fdie2=fdie4.wav
</white>

<green2>
name=Slimey Joe, the Green Guy's Brudda
fpic=fairy3.bmp
dpic=fairy3d1.bmp
worth=50
size=60
speed=300
intel=5
gift=1
hp=2
fdie1=fdie8.wav
fdie2=fdie4.wav
</green2>

<cavebitch>
name=Uglet
fpic=fairy7.bmp
dpic=fairy7d1.bmp
worth=200
speed=300
intel=1
hp=5
fdie1=fdie8.wav
fdie2=fdie7.wav
</cavebitch>

<afrofairy>
name=The Afrocan Queen
fcount=2
fpic=fboss1.bmp
dpic=fboss1.bmp
worth=12000
speed=300
intel=10
hp=1000
fdie1=fdie8.wav
fdie2=fdie7.wav
</afrofairy>

<glow>
name=Great Balls of Fairy
fpic=fairy4.bmp
dpic=fairy4d1.bmp
worth=50
size=50
speed=350
hp=2
intel=5
fdie1=fdie1.wav
fdie2=fdie3.wav
</glow>

<electric>
name=Elmo the Electro-Fairy
fpic=fairy6.bmp
dpic=fairy6d1.bmp
apic=fairy6a.bmp
rprob=5
asound=zzz.wav
worth=100
hp=20
speed=300
intel=15
gift=3
fdie1=fdie1.wav
fdie2=fdie2.wav
</electric>


<bikini>
name=Bikini Babe
fpic=fairy8.bmp
dpic=fairy8d1.bmp
worth=200
speed=500
hp=2
intel=4
fdie1=fdie8.wav
fdie2=fdie7.wav
</bikini>

<float>
name=Floater
fpic=fairy9.bmp
dpic=fairy9d1.bmp
apic=fairy9a.bmp
rprob=2
asound=putput.wav
worth=1000
speed=400
intel=10
fdie1=fdie1.wav
fdie2=fdie2.wav
</float>

</fairies>
